os:
  - linux
services:
  - docker
language: node_js
node_js:
  - '10.16.0'
jdk:
  - oraclejdk8
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
    - $HOME/.yarn-cache
env:
  global:
    - NODE_VERSION=10.16.0
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
    - secure: rH9D7ZKmOG/M65FyxJDSLN8D3CZ+aoesyQwqW/5ofCcSa8CBN/gsnMsb5h3B8up1/PDjyPaFAWXwgbSa+Ci66aelbvZo7c0qUH8F5nVvoiuUvOTchl6Tm1JLL9twzf3dbmj8zXJSueaLGeF1BsoqdVtTAl1YXkeS5OyZY8r8pU+xOyfSXOVtoIBMOrIOk0dyZs9wHoNlVHYSbeETyyJ/dTBXQftXqhk2mVdUoeAGW592hsz3qGp7o1vy2tVLwo7PMcUnHqaCjEd7BvEW8EIonEhxyvvPaVr4wAVetFrXHanZCpWe+Oi/5s5X0ZQJCOEXKh0vwEecTwdsMMTIHS7OidcVfebDtBRIciTcb56CLmoGMINJgcPaP5j0hUd1CpQdet5CwSOPg+OKUlIYTxaPvo+tUgcKWIBXSmL1s0lwy3jMQAkvDsedD44J15nEY7y0oJhvBuQ0wSlePPfcyB+pkMwxg0RpvnLJsHmB2+xfP0JSNqKV3c3MDtT382dnr6/RlWtnUJXWug9ncSVQptCmUS68/ZkbrbEenloSMrVDkTa/f/+QYVK1kOUOL8Dvo0g8v5YndFkKwjPR+IrFmP0m7etAFOtyj/PF5+kRzw1b1mnf/UtPU8SYeFgYKneKi7jaNDsi/g1GKU5eDDUczNEhR01vLil2NTF1YvMoIHYnsWs=
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - echo $super_secret_password | gpg --passphrase-fd 0 secrets.tar.gpg
  - tar xvf secrets.tar
install:
  - yarn install
script:
  - chmod +x mvnw
  - ./mvnw clean verify
  - ./mvnw com.github.eirslett:frontend-maven-plugin:yarn -Dfrontend.yarn.arguments='run test' -Dmaven.repo.local=$MAVEN_USER_HOME
  - ./mvnw org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.organization=python-sinhala-education-society -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
  - ./mvnw verify -Pprod -DskipTests
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/260eb3b570873affaad2
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
deploy:
  provider: gae
  keyfile: gcloudkey.json
  project: pythonsinhala-243503
  skip_cleanup: true
  on:
    tags: true
    condition: '$TRAVIS_TAG =~ ^v(.+)'
