runtime: java11
instance_class: F2
handlers:
- url: /(.*)
  script: auto
  secure: always
automatic_scaling:
  min_instances: 0
  max_instances: 1
entrypoint: java -Xmx4096M com.asanka.tutor.OpenLearnrApp
